\documentclass{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


\cite{Kasdin25} show that dopamine in the brains of young zebra finches acts as 
a learning signal, increasing when they sing closer to their adult song and 
decreasing when they sing further away, effectively guiding their vocal 
development through trial-and-error. This suggests that complex natural 
behaviors, like learning to sing, are shaped by dopamine-driven reinforcement 
learning, similar to how artificial intelligence learns. You can find the 
paper at this link:
\href{https://www.nature.com/articles/s41586-025-08729-1}{{https://www.nature.com/articles/s41586-025-08729-1}.}.

Note they measure dopamine using fibre photometry, changes in the fluorescence
indicate dopamine changes in realtime. Their specific measurement considers 
changes in flourescence in 100-ms windows between 200 and 300 ms from the start 
of singing, averaged across development.

\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONDUCT A POWER ANALYSIS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Using the \texttt{pwr} package for \texttt{R} \citep{pwr},
conduct a power analysis. How many observations would the researchers 
need to detect a moderate-to-large effect ($d=0.65$) when using 
$\alpha=0.05$ and default power (0.80) for a two-sided one sample 
$t$ test.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hldef{(pwr)}

\hldef{power.result} \hlkwb{<-} \hlkwd{pwr.t.test}\hldef{(}\hlkwc{d} \hldef{=} \hlnum{0.65}\hldef{,}
                           \hlkwc{sig.level} \hldef{=} \hlnum{0.05}\hldef{,}
                           \hlkwc{power} \hldef{=} \hlnum{0.80}\hldef{,}
                           \hlkwc{type} \hldef{=} \hlsng{"one.sample"}\hldef{,}
                           \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}
\hlkwd{print}\hldef{(power.result)}
\end{alltt}
\begin{verbatim}
## 
##      One-sample t test power calculation 
## 
##               n = 20.58039
##               d = 0.65
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
\end{verbatim}
\end{kframe}
\end{knitrout}

In order to detect a moderate-to-large effect ($d=0.65$) when using 
$\alpha=0.05$ and default power (0.80) for a two-sided one sample 
$t$ test, researchers should use a sample size of at least $n=21$.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% COLLECT DATA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Click the link to go to the paper. Find the source data for 
Figure 2. Download the Excel file. Describe what you needed to
do to collect the data for Figure 2(g). Note that you only need the 
\texttt{closer\_vals} and \texttt{further\_vals}. Ensure to 
\texttt{mutate()} the data to get a difference 
(e.g., \texttt{closer\_vals - further\_vals}).

In order to collect the data for figure 2(g), I would use the \texttt{g.Farther\_vals} (dopamine values when birds sang further away) and \texttt{g.Closer\_vals} (dopamine values when birds sang closer to the adult song) tabs in the excel file, and save each sheet as an individual CSV file. 

Once both CSV files are opened in R, I would create a tibble with two columns, one that represents the values in the Farther data, and one that represents the values in the Closer data.

Then, I would finally mutate the tibble and add a column that represents the difference between further and closer.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hldef{(tidyverse)}

\hldef{closer} \hlkwb{<-} \hlkwd{read_csv}\hldef{(}\hlsng{"g.Closer_vals.csv"}\hldef{)}
\end{alltt}


{\ttfamily\noindent\itshape\color{messagecolor}{\#\# Rows: 24 Columns: 1\\\#\# -- Column specification --------------------------------------------------------\\\#\# Delimiter: "{},"{}\\\#\# dbl (1): 0.275714146\\\#\# \\\#\# i Use `spec()` to retrieve the full column specification for this data.\\\#\# i Specify the column types or set `show\_col\_types = FALSE` to quiet this message.}}\begin{alltt}
\hldef{further} \hlkwb{<-} \hlkwd{read_csv}\hldef{(}\hlsng{"g.Farther_vals.csv"}\hldef{)}
\end{alltt}


{\ttfamily\noindent\itshape\color{messagecolor}{\#\# Rows: 24 Columns: 1\\\#\# -- Column specification --------------------------------------------------------\\\#\# Delimiter: "{},"{}\\\#\# dbl (1): -0.191685046\\\#\# \\\#\# i Use `spec()` to retrieve the full column specification for this data.\\\#\# i Specify the column types or set `show\_col\_types = FALSE` to quiet this message.}}\begin{alltt}
\hlkwd{colnames}\hldef{(closer)} \hlkwb{<-} \hlsng{"Value"}
\hlkwd{colnames}\hldef{(further)} \hlkwb{<-} \hlsng{"Value"}

\hldef{data} \hlkwb{<-} \hlkwd{tibble}\hldef{(}
  \hlkwc{closer.vals} \hldef{= closer}\hlopt{$}\hldef{Value,}
  \hlkwc{further.vals} \hldef{= further}\hlopt{$}\hldef{Value}
\hldef{)}

\hldef{data} \hlkwb{<-} \hldef{data |>}
  \hlkwd{mutate}\hldef{(}\hlkwc{diff} \hldef{= closer.vals} \hlopt{-} \hldef{further.vals)}
\end{alltt}
\end{kframe}
\end{knitrout}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SUMMARIZE DATA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Summarize the data.
\begin{enumerate}
  \item Summarize the further data. Do the data suggest that
   dopamine in the brains of young zebra finches decreases when
   they sing further away?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{further.summary} \hlkwb{<-} \hldef{data |>}
  \hlkwd{summarise}\hldef{(}
    \hlkwc{mean} \hldef{=} \hlkwd{mean}\hldef{(further.vals,} \hlkwc{na.rm} \hldef{=} \hlnum{TRUE}\hldef{),}
    \hlkwc{sd} \hldef{=} \hlkwd{sd}\hldef{(further.vals,} \hlkwc{na.rm} \hldef{=} \hlnum{TRUE}\hldef{),}
    \hlkwc{n} \hldef{=} \hlkwd{sum}\hldef{(}\hlopt{!}\hlkwd{is.na}\hldef{(further.vals))}
  \hldef{)}

\hldef{further.summary}
\end{alltt}
\begin{verbatim}
## # A tibble: 1 x 3
##     mean    sd     n
##    <dbl> <dbl> <int>
## 1 -0.203 0.133    24
\end{verbatim}
\end{kframe}
\end{knitrout}

  The mean is significantly less than 0, which supports the idea that dopamine  
  decreases when birds sing further away.
   
   \item Summarize the closer data. Do the data suggest that
   dopamine in the brains of young zebra finches increases when
   they sing closer to their adult song?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{summary.closer} \hlkwb{<-} \hldef{data |>}
  \hlkwd{summarise}\hldef{(}
    \hlkwc{mean} \hldef{=} \hlkwd{mean}\hldef{(closer.vals,} \hlkwc{na.rm} \hldef{=} \hlnum{TRUE}\hldef{),}
    \hlkwc{sd} \hldef{=} \hlkwd{sd}\hldef{(closer.vals,} \hlkwc{na.rm} \hldef{=} \hlnum{TRUE}\hldef{),}
    \hlkwc{n} \hldef{=} \hlkwd{sum}\hldef{(}\hlopt{!}\hlkwd{is.na}\hldef{(closer.vals))}
  \hldef{)}

\hldef{summary.closer}
\end{alltt}
\begin{verbatim}
## # A tibble: 1 x 3
##    mean     sd     n
##   <dbl>  <dbl> <int>
## 1 0.151 0.0927    24
\end{verbatim}
\end{kframe}
\end{knitrout}
  
  The mean is greater than 0, which suggests that dopamine increases when birds sing closer to the target.
   
  \item Summarize the paired differences. Do the data suggest
  that there is a difference between dopamine in the brains of
  young zebra finches when they sing further away compared to 
  closer to their adult song?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{summary.diff} \hlkwb{<-} \hldef{data |>}
  \hlkwd{summarise}\hldef{(}
    \hlkwc{mean} \hldef{=} \hlkwd{mean}\hldef{(diff,} \hlkwc{na.rm} \hldef{=} \hlnum{TRUE}\hldef{),}
    \hlkwc{sd} \hldef{=} \hlkwd{sd}\hldef{(diff,} \hlkwc{na.rm} \hldef{=} \hlnum{TRUE}\hldef{),}
    \hlkwc{n} \hldef{=} \hlkwd{sum}\hldef{(}\hlopt{!}\hlkwd{is.na}\hldef{(diff))}
  \hldef{)}

\hldef{summary.diff}
\end{alltt}
\begin{verbatim}
## # A tibble: 1 x 3
##    mean    sd     n
##   <dbl> <dbl> <int>
## 1 0.354 0.214    24
\end{verbatim}
\end{kframe}
\end{knitrout}

  The mean is positive, which implies higher dopamine when singing closer vs. further.
  
  \item \textbf{Optional Challenge:} Can you reproduce Figure 2(g)?
  Note that the you can use \texttt{geom\_errorbar()} to plot
  the range created by adding the mean $\pm$ one standard deviation.
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONDUCT THE TESTS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Conduct the inferences they do in the paper. Make sure to report the results
a little more comprehensively -- that is your parenthetical should look something
like: ($t=23.99$, $p<0.0001$; $g=1.34$; 95\% CI: 4.43, 4.60).\\
\textbf{Note:} Your numbers may vary slightly as they performed some unclear
correction of their $p$-values. I'm waiting to hear back from them via email!
\begin{enumerate}
  \item ``The close responses differed significantly from 0 ($p=1.63 \times 10^{-8}$).''
  \item ``The far responses differed significantly from 0 ($p=5.17 \times 10^{-8}$).''
  \item ``The difference between populations was significant ($p=1.04 \times10^{-8}$).''
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(t.closer} \hlkwb{<-} \hlkwd{t.test}\hldef{(data}\hlopt{$}\hldef{closer.vals,} \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{))}
\end{alltt}
\begin{verbatim}
## 
## 	One Sample t-test
## 
## data:  data$closer.vals
## t = 7.9945, df = 23, p-value = 4.34e-08
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.1121084 0.1903801
## sample estimates:
## mean of x 
## 0.1512443
\end{verbatim}
\begin{alltt}
\hldef{(t.further} \hlkwb{<-} \hlkwd{t.test}\hldef{(data}\hlopt{$}\hldef{further.vals,} \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{))}
\end{alltt}
\begin{verbatim}
## 
## 	One Sample t-test
## 
## data:  data$further.vals
## t = -7.4785, df = 23, p-value = 1.337e-07
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.2593882 -0.1469806
## sample estimates:
##  mean of x 
## -0.2031844
\end{verbatim}
\begin{alltt}
\hldef{(t.paired} \hlkwb{<-} \hlkwd{t.test}\hldef{(data}\hlopt{$}\hldef{closer.vals, data}\hlopt{$}\hldef{further.vals,} \hlkwc{paired} \hldef{=} \hlnum{TRUE}\hldef{))}
\end{alltt}
\begin{verbatim}
## 
## 	Paired t-test
## 
## data:  data$closer.vals and data$further.vals
## t = 8.1073, df = 23, p-value = 3.41e-08
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.2639927 0.4448646
## sample estimates:
## mean difference 
##       0.3544287
\end{verbatim}
\begin{alltt}
\hlkwd{library}\hldef{(effectsize)}

\hldef{g.closer} \hlkwb{<-} \hlkwd{hedges_g}\hldef{(data}\hlopt{$}\hldef{closer.vals,} \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{)}
\hldef{(g.closer)}
\end{alltt}
\begin{verbatim}
## Hedges' g |       95% CI
## ------------------------
## 1.58      | [0.97, 2.17]
\end{verbatim}
\begin{alltt}
\hldef{g.further} \hlkwb{<-} \hlkwd{hedges_g}\hldef{(data}\hlopt{$}\hldef{further.vals,} \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{)}
\hldef{(g.further)}
\end{alltt}
\begin{verbatim}
## Hedges' g |         95% CI
## --------------------------
## -1.48     | [-2.04, -0.89]
\end{verbatim}
\begin{alltt}
\hldef{g.diff} \hlkwb{<-} \hlkwd{hedges_g}\hldef{(data}\hlopt{$}\hldef{closer.vals, data}\hlopt{$}\hldef{further.vals,} \hlkwc{paired} \hldef{=} \hlnum{TRUE}\hldef{)}
\end{alltt}


{\ttfamily\noindent\itshape\color{messagecolor}{\#\# For paired samples, 'repeated\_measures\_d()' provides more options.}}\begin{alltt}
\hldef{(g.diff)}
\end{alltt}
\begin{verbatim}
## Hedges' g |       95% CI
## ------------------------
## 1.60      | [0.99, 2.19]
\end{verbatim}
\end{kframe}
\end{knitrout}

For the close responses, there is statistically discernible support for the researcher’s alternative hypothesis ($t=7.9945$,$p=4.34 \times 10^{-8}$, $g=1.58$, 95\% CI: 0.1121, 0.1903).

For the far responses, there is statistically discernible support for the researcher’s alternative hypothesis ($t=-7.4785$,$p=1.337 \times 10^{-7}$, $g=-1.48$, 95\% CI: -0.2593, -0.1469).

For the difference between close and far responses, there is statistically discernible support for the researcher’s alternative hypothesis ($t=8.1073$,$p=3.41 \times 10^{-8}$, $g=1.60$, 95\% CI: 0.2639, 0.4448).
  
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CONDUCT THE TESTS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Reverse engineer the hypothesis test plot from Lecture 20 to create accurate
hypothesis testing plots for each part of the previous question.
\begin{enumerate}
  \item Question 4, part(a).
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{x} \hlkwb{<-} \hldef{data}\hlopt{$}\hldef{further.vals}
\hldef{mu0} \hlkwb{<-} \hlnum{0}
\hldef{xbar} \hlkwb{<-} \hlkwd{mean}\hldef{(x)}
\hldef{s} \hlkwb{<-} \hlkwd{sd}\hldef{(x)}
\hldef{n} \hlkwb{<-} \hlkwd{length}\hldef{(x)}
\hldef{t.stat} \hlkwb{<-} \hldef{(xbar} \hlopt{-} \hldef{mu0)}\hlopt{/}\hldef{(s}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}

\hldef{R} \hlkwb{<-} \hlnum{1000}
\hldef{resamples} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{=} \hlkwd{numeric}\hldef{(R))}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R)\{}
  \hldef{curr.sample} \hlkwb{<-} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{= x,} \hlkwc{size} \hldef{= n,} \hlkwc{replace} \hldef{=} \hlnum{TRUE}\hldef{)}
  \hldef{resamples}\hlopt{$}\hldef{t[i]} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(curr.sample)} \hlopt{-} \hldef{mu0)}\hlopt{/}\hldef{(}\hlkwd{sd}\hldef{(curr.sample)}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}
\hldef{\}}

\hldef{ggdat.t} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{=} \hlkwd{seq}\hldef{(}\hlopt{-}\hlnum{5}\hldef{,} \hlnum{5}\hldef{,} \hlkwc{length.out} \hldef{=} \hlnum{1000}\hldef{)) |>}
  \hlkwd{mutate}\hldef{(}\hlkwc{pdf.null} \hldef{=} \hlkwd{dt}\hldef{(t,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{))}
\hldef{ggdat.obs} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{= t.stat,} \hlkwc{y} \hldef{=} \hlnum{0}\hldef{)}

\hldef{t.breaks} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlopt{-}\hlnum{5}\hldef{,} \hlkwd{qt}\hldef{(}\hlnum{0.025}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{),} \hlnum{0}\hldef{,} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{),} \hlnum{5}\hldef{, t.stat)}
\hldef{xbar.breaks} \hlkwb{<-} \hldef{t.breaks} \hlopt{*} \hldef{s}\hlopt{/}\hldef{(}\hlkwd{sqrt}\hldef{(n))} \hlopt{+} \hldef{mu0}

\hlkwd{ggplot}\hldef{()} \hlopt{+}
  \hlkwd{geom_line}\hldef{(}\hlkwc{data} \hldef{= ggdat.t,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{y} \hldef{= pdf.null))} \hlopt{+}
  \hlkwd{geom_hline}\hldef{(}\hlkwc{yintercept} \hldef{=} \hlnum{0}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{<=} \hlkwd{qt}\hldef{(}\hlnum{0.025}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{)),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"darkblue"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.5}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{>=} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{)),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"darkblue"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.5}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{>=} \hldef{t.stat),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"red"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.25}\hldef{)} \hlopt{+}
  \hlkwd{geom_point}\hldef{(}\hlkwc{data} \hldef{= ggdat.obs,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{y} \hldef{= y),} \hlkwc{color} \hldef{=} \hlsng{"red"}\hldef{)} \hlopt{+}
  \hlkwd{stat_density}\hldef{(}\hlkwc{data} \hldef{= resamples,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t),} \hlkwc{geom} \hldef{=} \hlsng{"line"}\hldef{,} \hlkwc{color} \hldef{=} \hlsng{"darkblue"}\hldef{)} \hlopt{+}
  \hlkwd{ylab}\hldef{(}\hlsng{"Density"}\hldef{)}
\end{alltt}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-8-1} 
\end{knitrout}
  \item Question 4, part(b).
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{x} \hlkwb{<-} \hldef{data}\hlopt{$}\hldef{closer.vals}
\hldef{mu0} \hlkwb{<-} \hlnum{0}
\hldef{xbar} \hlkwb{<-} \hlkwd{mean}\hldef{(x)}
\hldef{s} \hlkwb{<-} \hlkwd{sd}\hldef{(x)}
\hldef{n} \hlkwb{<-} \hlkwd{length}\hldef{(x)}
\hldef{t.stat} \hlkwb{<-} \hldef{(xbar} \hlopt{-} \hldef{mu0)}\hlopt{/}\hldef{(s}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}

\hldef{R} \hlkwb{<-} \hlnum{1000}
\hldef{resamples} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{=} \hlkwd{numeric}\hldef{(R))}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R)\{}
  \hldef{curr.sample} \hlkwb{<-} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{= x,} \hlkwc{size} \hldef{= n,} \hlkwc{replace} \hldef{=} \hlnum{TRUE}\hldef{)}
  \hldef{resamples}\hlopt{$}\hldef{t[i]} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(curr.sample)} \hlopt{-} \hldef{mu0)}\hlopt{/}\hldef{(}\hlkwd{sd}\hldef{(curr.sample)}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}
\hldef{\}}

\hldef{ggdat.t} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{=} \hlkwd{seq}\hldef{(}\hlopt{-}\hlnum{5}\hldef{,} \hlnum{5}\hldef{,} \hlkwc{length.out} \hldef{=} \hlnum{1000}\hldef{)) |>}
  \hlkwd{mutate}\hldef{(}\hlkwc{pdf.null} \hldef{=} \hlkwd{dt}\hldef{(t,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{))}
\hldef{ggdat.obs} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{= t.stat,} \hlkwc{y} \hldef{=} \hlnum{0}\hldef{)}

\hldef{t.breaks} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlopt{-}\hlnum{5}\hldef{,} \hlkwd{qt}\hldef{(}\hlnum{0.025}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{),} \hlnum{0}\hldef{,} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{),} \hlnum{5}\hldef{, t.stat)}
\hldef{xbar.breaks} \hlkwb{<-} \hldef{t.breaks} \hlopt{*} \hldef{s}\hlopt{/}\hldef{(}\hlkwd{sqrt}\hldef{(n))} \hlopt{+} \hldef{mu0}

\hlkwd{ggplot}\hldef{()} \hlopt{+}
  \hlkwd{geom_line}\hldef{(}\hlkwc{data} \hldef{= ggdat.t,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{y} \hldef{= pdf.null))} \hlopt{+}
  \hlkwd{geom_hline}\hldef{(}\hlkwc{yintercept} \hldef{=} \hlnum{0}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{<=} \hlkwd{qt}\hldef{(}\hlnum{0.025}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{)),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"darkblue"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.5}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{>=} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{)),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"darkblue"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.5}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{>=} \hldef{t.stat),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"red"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.25}\hldef{)} \hlopt{+}
  \hlkwd{geom_point}\hldef{(}\hlkwc{data} \hldef{= ggdat.obs,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{y} \hldef{= y),} \hlkwc{color} \hldef{=} \hlsng{"red"}\hldef{)} \hlopt{+}
  \hlkwd{stat_density}\hldef{(}\hlkwc{data} \hldef{= resamples,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t),} \hlkwc{geom} \hldef{=} \hlsng{"line"}\hldef{,} \hlkwc{color} \hldef{=} \hlsng{"darkblue"}\hldef{)} \hlopt{+}
  \hlkwd{ylab}\hldef{(}\hlsng{"Density"}\hldef{)}
\end{alltt}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-9-1} 
\end{knitrout}
  \item Question 4, part(c).
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
  \hldef{x} \hlkwb{<-} \hldef{data}\hlopt{$}\hldef{closer.vals} \hlopt{-} \hldef{data}\hlopt{$}\hldef{further.vals}
\hldef{mu0} \hlkwb{<-} \hlnum{0}
\hldef{xbar} \hlkwb{<-} \hlkwd{mean}\hldef{(x)}
\hldef{s} \hlkwb{<-} \hlkwd{sd}\hldef{(x)}
\hldef{n} \hlkwb{<-} \hlkwd{length}\hldef{(x)}
\hldef{t.stat} \hlkwb{<-} \hldef{(xbar} \hlopt{-} \hldef{mu0)}\hlopt{/}\hldef{(s}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}

\hldef{R} \hlkwb{<-} \hlnum{1000}
\hldef{resamples} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{=} \hlkwd{numeric}\hldef{(R))}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R)\{}
  \hldef{curr.sample} \hlkwb{<-} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{= x,} \hlkwc{size} \hldef{= n,} \hlkwc{replace} \hldef{=} \hlnum{TRUE}\hldef{)}
  \hldef{resamples}\hlopt{$}\hldef{t[i]} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(curr.sample)} \hlopt{-} \hldef{mu0)}\hlopt{/}\hldef{(}\hlkwd{sd}\hldef{(curr.sample)}\hlopt{/}\hlkwd{sqrt}\hldef{(n))}
\hldef{\}}

\hldef{ggdat.t} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{=} \hlkwd{seq}\hldef{(}\hlopt{-}\hlnum{5}\hldef{,} \hlnum{5}\hldef{,} \hlkwc{length.out} \hldef{=} \hlnum{1000}\hldef{)) |>}
  \hlkwd{mutate}\hldef{(}\hlkwc{pdf.null} \hldef{=} \hlkwd{dt}\hldef{(t,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{))}
\hldef{ggdat.obs} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{t} \hldef{= t.stat,} \hlkwc{y} \hldef{=} \hlnum{0}\hldef{)}

\hldef{t.breaks} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlopt{-}\hlnum{5}\hldef{,} \hlkwd{qt}\hldef{(}\hlnum{0.025}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{),} \hlnum{0}\hldef{,} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{),} \hlnum{5}\hldef{, t.stat)}
\hldef{xbar.breaks} \hlkwb{<-} \hldef{t.breaks} \hlopt{*} \hldef{s}\hlopt{/}\hldef{(}\hlkwd{sqrt}\hldef{(n))} \hlopt{+} \hldef{mu0}

\hlkwd{ggplot}\hldef{()} \hlopt{+}
  \hlkwd{geom_line}\hldef{(}\hlkwc{data} \hldef{= ggdat.t,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{y} \hldef{= pdf.null))} \hlopt{+}
  \hlkwd{geom_hline}\hldef{(}\hlkwc{yintercept} \hldef{=} \hlnum{0}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{<=} \hlkwd{qt}\hldef{(}\hlnum{0.025}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{)),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"darkblue"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.5}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{>=} \hlkwd{qt}\hldef{(}\hlnum{0.975}\hldef{,} \hlkwc{df} \hldef{= n} \hlopt{-} \hlnum{1}\hldef{)),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"darkblue"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.5}\hldef{)} \hlopt{+}
  \hlkwd{geom_ribbon}\hldef{(}\hlkwc{data} \hldef{=} \hlkwd{subset}\hldef{(ggdat.t, t} \hlopt{>=} \hldef{t.stat),}
              \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{ymin} \hldef{=} \hlnum{0}\hldef{,} \hlkwc{ymax} \hldef{= pdf.null),} \hlkwc{fill} \hldef{=} \hlsng{"red"}\hldef{,} \hlkwc{alpha} \hldef{=} \hlnum{0.25}\hldef{)} \hlopt{+}
  \hlkwd{geom_point}\hldef{(}\hlkwc{data} \hldef{= ggdat.obs,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{y} \hldef{= y),} \hlkwc{color} \hldef{=} \hlsng{"red"}\hldef{)} \hlopt{+}
  \hlkwd{stat_density}\hldef{(}\hlkwc{data} \hldef{= resamples,} \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t),} \hlkwc{geom} \hldef{=} \hlsng{"line"}\hldef{,} \hlkwc{color} \hldef{=} \hlsng{"darkblue"}\hldef{)} \hlopt{+}
  \hlkwd{ylab}\hldef{(}\hlsng{"Density"}\hldef{)}
\end{alltt}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-10-1} 
\end{knitrout}
\end{enumerate}
\end{enumerate}


\bibliography{bibliography}
\end{document}
